# Generated by Django 5.2.6 on 2025-09-26 20:54

import django.core.validators
import django.db.models.deletion
import resume_analyzer.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Resume',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Name of the person (optional)', max_length=255)),
                ('email', models.EmailField(blank=True, help_text='Email address (optional)', max_length=254, null=True)),
                ('file', models.FileField(help_text='Upload PDF or Word document', upload_to=resume_analyzer.models.resume_upload_path, validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['pdf', 'docx', 'doc'])])),
                ('original_filename', models.CharField(max_length=255)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('processed', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='JobKeyword',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('industry', models.CharField(choices=[('tech', 'Technology'), ('finance', 'Finance'), ('healthcare', 'Healthcare'), ('marketing', 'Marketing'), ('sales', 'Sales'), ('education', 'Education'), ('general', 'General')], max_length=20)),
                ('keyword', models.CharField(max_length=100)),
                ('weight', models.FloatField(default=1.0, help_text='Importance weight for this keyword')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'unique_together': {('industry', 'keyword')},
            },
        ),
        migrations.CreateModel(
            name='ATSAnalysis',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('extracted_text', models.TextField(help_text='Raw text extracted from resume')),
                ('word_count', models.IntegerField(default=0)),
                ('overall_score', models.FloatField(default=0.0, help_text='Overall ATS compatibility score (0-100)')),
                ('has_clear_sections', models.BooleanField(default=False)),
                ('has_contact_info', models.BooleanField(default=False)),
                ('has_work_experience', models.BooleanField(default=False)),
                ('has_education', models.BooleanField(default=False)),
                ('has_skills', models.BooleanField(default=False)),
                ('keyword_density', models.FloatField(default=0.0, help_text='Percentage of relevant keywords')),
                ('readability_score', models.FloatField(default=0.0, help_text='Flesch reading ease score')),
                ('has_images', models.BooleanField(default=False, help_text='Contains images or graphics')),
                ('has_tables', models.BooleanField(default=False, help_text='Contains tables')),
                ('has_special_characters', models.BooleanField(default=False, help_text='Contains special characters')),
                ('recommendations', models.TextField(blank=True, help_text='Suggestions for improvement')),
                ('analyzed_at', models.DateTimeField(auto_now_add=True)),
                ('analysis_version', models.CharField(default='1.0', max_length=10)),
                ('resume', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='analysis', to='resume_analyzer.resume')),
            ],
        ),
    ]
