# Generated by Django 5.2.6 on 2025-09-29 22:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resume_analyzer', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='atsanalysis',
            name='additional_data',
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
